[package]
name = "v13"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
hashbrown = "0.15.2"
peekmore = "1.3.0"
rustix = { version = "0.38.44", features = ["termios"] }
windows-sys = { version = "0.59.0", features = ["Win32", "Win32_System", "Win32_System_Console"] }
